<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Suite" duration-ms="37912" started-at="2020-01-30T09:31:40Z" finished-at="2020-01-30T09:32:18Z">
    <groups>
    </groups>
    <test name="Test" duration-ms="37912" started-at="2020-01-30T09:31:40Z" finished-at="2020-01-30T09:32:18Z">
      <class name="testCases.TC001">
        <test-method status="PASS" signature="setUp()[pri:0, instance:testCases.TC001@646be2c3]" name="setUp" is-config="true" duration-ms="187" started-at="2020-01-30T15:01:40Z" finished-at="2020-01-30T15:01:40Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="PASS" signature="bf()[pri:0, instance:testCases.TC001@646be2c3]" name="bf" is-config="true" duration-ms="4" started-at="2020-01-30T15:01:40Z" finished-at="2020-01-30T15:01:40Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- bf -->
        <test-method status="FAIL" signature="TC_0001()[pri:0, instance:testCases.TC001@646be2c3]" name="TC_0001" duration-ms="33781" started-at="2020-01-30T15:01:40Z" finished-at="2020-01-30T15:02:14Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:496)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at org.testng.Assert.assertTrue(Assert.java:52)
	at testCases.TC001.TC_0001(TC001.java:37)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1191)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1116)
	at org.testng.TestNG.run(TestNG.java:1024)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:283)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:120)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC_0001 -->
        <test-method status="PASS" signature="getResult(org.testng.ITestResult)[pri:0, instance:testCases.TC001@646be2c3]" name="getResult" is-config="true" duration-ms="805" started-at="2020-01-30T15:02:14Z" finished-at="2020-01-30T15:02:15Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=TC_0001 status=FAILURE method=TC001.TC_0001()[pri:0, instance:testCases.TC001@646be2c3] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getResult -->
        <test-method status="PASS" signature="TearDown()[pri:0, instance:testCases.TC001@646be2c3]" name="TearDown" is-config="true" duration-ms="3291" started-at="2020-01-30T15:02:15Z" finished-at="2020-01-30T15:02:18Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TearDown -->
        <test-method status="PASS" signature="AfterTest()[pri:0, instance:testCases.TC001@646be2c3]" name="AfterTest" is-config="true" duration-ms="0" started-at="2020-01-30T15:02:18Z" finished-at="2020-01-30T15:02:18Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- AfterTest -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:testCases.TC001@646be2c3]" name="tearDown" is-config="true" duration-ms="575" started-at="2020-01-30T15:02:18Z" finished-at="2020-01-30T15:02:19Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- testCases.TC001 -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
